// Code generated by mockery v2.32.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Kill is an autogenerated mock type for the Kill type
type Kill struct {
	mock.Mock
}

type Kill_Expecter struct {
	mock *mock.Mock
}

func (_m *Kill) EXPECT() *Kill_Expecter {
	return &Kill_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx, definitionName, instanceName, autoApprove, vars
func (_m *Kill) Run(ctx context.Context, definitionName string, instanceName string, autoApprove bool, vars []string) error {
	ret := _m.Called(ctx, definitionName, instanceName, autoApprove, vars)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool, []string) error); ok {
		r0 = rf(ctx, definitionName, instanceName, autoApprove, vars)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Kill_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Kill_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - definitionName string
//   - instanceName string
//   - autoApprove bool
//   - vars []string
func (_e *Kill_Expecter) Run(ctx interface{}, definitionName interface{}, instanceName interface{}, autoApprove interface{}, vars interface{}) *Kill_Run_Call {
	return &Kill_Run_Call{Call: _e.mock.On("Run", ctx, definitionName, instanceName, autoApprove, vars)}
}

func (_c *Kill_Run_Call) Run(run func(ctx context.Context, definitionName string, instanceName string, autoApprove bool, vars []string)) *Kill_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool), args[4].([]string))
	})
	return _c
}

func (_c *Kill_Run_Call) Return(_a0 error) *Kill_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Kill_Run_Call) RunAndReturn(run func(context.Context, string, string, bool, []string) error) *Kill_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewKill creates a new instance of Kill. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKill(t interface {
	mock.TestingT
	Cleanup(func())
}) *Kill {
	mock := &Kill{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
