// Code generated by mockery v2.32.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Spawn is an autogenerated mock type for the Spawn type
type Spawn struct {
	mock.Mock
}

type Spawn_Expecter struct {
	mock *mock.Mock
}

func (_m *Spawn) EXPECT() *Spawn_Expecter {
	return &Spawn_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx, definitionName, instanceName, dependenciesInstance, vars
func (_m *Spawn) Run(ctx context.Context, definitionName string, instanceName string, dependenciesInstance map[string]string, vars []string) error {
	ret := _m.Called(ctx, definitionName, instanceName, dependenciesInstance, vars)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]string, []string) error); ok {
		r0 = rf(ctx, definitionName, instanceName, dependenciesInstance, vars)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Spawn_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Spawn_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - definitionName string
//   - instanceName string
//   - dependenciesInstance map[string]string
//   - vars []string
func (_e *Spawn_Expecter) Run(ctx interface{}, definitionName interface{}, instanceName interface{}, dependenciesInstance interface{}, vars interface{}) *Spawn_Run_Call {
	return &Spawn_Run_Call{Call: _e.mock.On("Run", ctx, definitionName, instanceName, dependenciesInstance, vars)}
}

func (_c *Spawn_Run_Call) Run(run func(ctx context.Context, definitionName string, instanceName string, dependenciesInstance map[string]string, vars []string)) *Spawn_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(map[string]string), args[4].([]string))
	})
	return _c
}

func (_c *Spawn_Run_Call) Return(_a0 error) *Spawn_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Spawn_Run_Call) RunAndReturn(run func(context.Context, string, string, map[string]string, []string) error) *Spawn_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewSpawn creates a new instance of Spawn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpawn(t interface {
	mock.TestingT
	Cleanup(func())
}) *Spawn {
	mock := &Spawn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
